export const PRODUCT_CATEGORIES = {
  FASHION_AND_ACCESSORIES: "FASHION_AND_ACCESSORIES",
  ELECTRONICS: "ELECTRONICS",
  HOME_AND_DECOR: "HOME_AND_DECOR",
  SPORTS_AND_OUTDOORS: "SPORTS_AND_OUTDOORS",
  BEAUTY_AND_HEALTH: "BEAUTY_AND_HEALTH",
  BABY_AND_KIDS: "BABY_AND_KIDS",
  AUTOMOTIVE: "AUTOMOTIVE",
  FOOD: "FOOD",
} as const;

export const PRODUCT_CATEGORY_LABELS = {
  [PRODUCT_CATEGORIES.FASHION_AND_ACCESSORIES]: "Fashion & Accessories",
  [PRODUCT_CATEGORIES.ELECTRONICS]: "Electronics",
  [PRODUCT_CATEGORIES.HOME_AND_DECOR]: "Home & Decor",
  [PRODUCT_CATEGORIES.SPORTS_AND_OUTDOORS]: "Sports & Outdoors",
  [PRODUCT_CATEGORIES.BEAUTY_AND_HEALTH]: "Beauty & Health",
  [PRODUCT_CATEGORIES.BABY_AND_KIDS]: "Baby & Kids",
  [PRODUCT_CATEGORIES.AUTOMOTIVE]: "Automotive",
  [PRODUCT_CATEGORIES.FOOD]: "Food & Beverages",
} as const;

export const PRODUCT_CATEGORY_OPTIONS = [
  {
    value: PRODUCT_CATEGORIES.FASHION_AND_ACCESSORIES,
    label: PRODUCT_CATEGORY_LABELS[PRODUCT_CATEGORIES.FASHION_AND_ACCESSORIES],
  },
  {
    value: PRODUCT_CATEGORIES.ELECTRONICS,
    label: PRODUCT_CATEGORY_LABELS[PRODUCT_CATEGORIES.ELECTRONICS],
  },
  {
    value: PRODUCT_CATEGORIES.HOME_AND_DECOR,
    label: PRODUCT_CATEGORY_LABELS[PRODUCT_CATEGORIES.HOME_AND_DECOR],
  },
  {
    value: PRODUCT_CATEGORIES.SPORTS_AND_OUTDOORS,
    label: PRODUCT_CATEGORY_LABELS[PRODUCT_CATEGORIES.SPORTS_AND_OUTDOORS],
  },
  {
    value: PRODUCT_CATEGORIES.BEAUTY_AND_HEALTH,
    label: PRODUCT_CATEGORY_LABELS[PRODUCT_CATEGORIES.BEAUTY_AND_HEALTH],
  },
  {
    value: PRODUCT_CATEGORIES.BABY_AND_KIDS,
    label: PRODUCT_CATEGORY_LABELS[PRODUCT_CATEGORIES.BABY_AND_KIDS],
  },
  {
    value: PRODUCT_CATEGORIES.AUTOMOTIVE,
    label: PRODUCT_CATEGORY_LABELS[PRODUCT_CATEGORIES.AUTOMOTIVE],
  },
  {
    value: PRODUCT_CATEGORIES.FOOD,
    label: PRODUCT_CATEGORY_LABELS[PRODUCT_CATEGORIES.FOOD],
  },
];
